name: Releases
on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "mohite770.pm@gmail.com"
        git config --local user.name "Pratikkumar Mohite"

    - name: Create and push Git tag
      run: |
        # Fetch the latest tags
        git fetch --tags    

      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}