# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: workflow

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]
  workflow_dispatch:

jobs:
  workflow:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    # - name: Install dependencies
    #   run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./src
